### ISSUE TITLE
Error while checking download version

### ISSUE THREAD

**Issue by didierterrien** [pbi-tools/pbi-tools#309] opened 2023-10-30 14:19 UTC
Hello Mathias,

"info  /checkDownloadVersion:true" returns the following error  (object reference issue):

> Failed to retrieve download info for Power BI Desktop.
> System.NullReferenceException: La r‚f‚rence d'objet n'est pas d‚finie … une instance d'un objet.
>    … PbiTools.Utils.PowerBIDownloader.TryFetchInfo(PowerBIDownloadInfo& info) dans X:\pbi-tools\BRANCHES\fody\src\PBI-Tools\Utils\PowerBIDownloader.cs:ligne 22

I use 1.0.0-rc.4 (TMDL Preview-2) but it's the same with a version from last year.

Thanks in advance

**Comment by mthierba** [comment] 2023-11-28 08:33
I'm aware - the Microsoft Downloads page changed, and I need to adjust the extraction logic.

**Comment by mthierba** [comment] 2023-11-28 08:36
Closing as duplicate of #298

**Closed by mthierba** 2023-11-28 08:36 UTC
