### ISSUE TITLE
pbi-tools info - Access is denied

### ISSUE THREAD

**Issue by MarcusWegener** [pbi-tools/pbi-tools#109] opened 2022-03-21 13:55 UTC
Hi,

i get the following error message when i run the  command "pbi-tools info" on my AzureVM.

pbi-tools.1.0.0-rc.1
OS Name: Microsoft Windows Server 2019 Datacenter
Version: 10.0.17763 Build 17763

PS C:\VS Code\Adventure Works> pbi-tools info
An unhandled exception occurred.
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at PbiTools.Utils.PowerBIProcesses.<EnumerateProcesses>d__1.MoveNext() in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Utils\PowerBIProcesses.cs:line 64
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at PbiTools.Cli.CmdLineActions.Info(Boolean checkDownloadVersion) in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Cli\Info.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Program.cs:line 94

**Comment by mthierba** [comment] 2022-03-21 14:31
Interesting! Haven't seen this one before (or at least no one's reported it!)

Your VM seems to be locked down somehow when iterating through processes. 

Just to clarify - did you unblock the ZIP before unpacking it?

**Comment by mthierba** [comment] 2022-03-21 14:32
Also, do you have SQL Server running on that same machine?

**Comment by MarcusWegener** [comment] 2022-03-22 15:31
Hi,
I had not unblocked the ZIP before unpacking.
I have now unlocked the ZIP and unzipped again, with the same result.

Yes, there is also a SQL Server running on the same machine.
I use this VM Image
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoft-dsvm.dsvm-win-2019?tab=Overview

**Comment by mthierba** [comment] 2022-03-22 15:43
Yes, that's what I thought. Easy to resolve then. pbi-tools is basically going through all processes called "msmdsrv", assuming those are linked to local PBI Desktop instances. SQL Server SSAS, however, if installed in the same machine, also has a proc running with the same name. Will just need to ignore those. Thanks for reporting! That'll be fixed in the next release.

**Comment by mthierba** [comment] 2022-04-05 15:12
@HankDank This is going to be fixed in the upcoming RC.2 release. For now, either ignore or stop the SSAS instance on your development machine.

**Comment by HankDank** [comment] 2022-04-06 06:31
@mthierba Okay thanks for the response Mathias.

**Comment by mthierba** [comment] 2022-05-01 07:21
@MarcusWegener @HankDank Would you mind testing your scenario again with the tool version at https://github.com/pbi-tools/pbi-tools/releases/tag/1.0.0-rc2.%2B20220501 This one has what I think is a fix, but I can't easily replicate your setup on my end.

**Comment by mthierba** [comment] 2022-05-01 07:47
Note, I updated the release link above - got the numbering wrong before.

**Comment by MarcusWegener** [comment] 2022-05-01 18:25
@mthierba Now it works for me.😊

PS C:\VS Code\Template> pbi-tools.exe info
{
  "version": "1.0.0-rc.2+20220501",
  "edition": "Desktop",
  "build": "1.0.22121.0714",
  "pbixProjVersion": "0.11",
  "pbiBuildVersion": "2.102.845.0",
  "amoVersion": "19.39.0.0",
  "toolPath": "C:\\pbi-tools.1.0.0-rc.2\\pbi-tools.exe",
  "locale": {
    "system": "en-DE (8192)",
    "ui": "en-US (1033)"
  },
  "settings": {
    "PBITOOLS_LogLevel": null,
    "PBITOOLS_PbiInstallDir": null,
    "PBITOOLS_AppDataDir": null,
    "PBITOOLS_Debug": null,
    "PBITOOLS_UICulture": null
  },
  "runtime": {
    "platform": "Microsoft Windows 10.0.17763 ",
    "architecture": "X64",
    "framework": ".NET Framework 4.7.3910.0"
  },
  "pbiInstalls": [
    {
      "ProductVersion": "2.104.941.0 (22.04)",
      "Is64Bit": true,
      "InstallDir": "C:\\Program Files\\Microsoft Power BI Desktop\\bin",
      "SettingsDir": "C:\\Users\\PBIAdmin\\AppData\\Local\\Microsoft\\Power BI Desktop",
      "Location": "Installer"
    }
  ],
  "effectivePbiInstallDir": "C:\\Program Files\\Microsoft Power BI Desktop\\bin",
  "pbiSessions": [
    {
      "ProductName": "Microsoft Power BI Desktop",
      "ProductVersion": "2.104.941.0 (22.04)",
      "ExePath": "C:\\Program Files\\Microsoft Power BI Desktop\\bin\\PBIDesktop.exe",
      "ProcessId": 5396,
      "Port": 50096,
      "WorkspaceName": "AnalysisServicesWorkspace_9f3bd068-3033-4dfb-aafb-79ef88b6b37e",
      "WorkspaceDir": "C:\\Users\\PBIAdmin\\AppData\\Local\\Microsoft\\Power BI Desktop\\AnalysisServicesWorkspaces\\AnalysisServicesWorkspace_9f3bd068-3033-4dfb-aafb-79ef88b6b37e\\Data",
      "PbixPath": null
    }
  ]
}

**Comment by mthierba** [comment] 2022-05-02 03:31
Thanks for confirming @MarcusWegener !

**Comment by matherring** [comment] 2022-05-25 05:01
I'm still encountering much the same issue as Marcus after testing with 1.0.0-rc.2+20220501. The machine I'm using is definitely locked down to some extent and is a VM shared by many users. Cannot see whether SSAS is running somewhere on the machine under someone else's profile, but I would assume that it is. 

E:\Users\mathewher (B9C3CFB3)\Desktop\pbi-tools>pbi-tools info
An unhandled exception occurred.
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at PbiTools.Win32.ProcessExtensions.GetCommandLine(Process process) in F:\pbi-tools\BRANCHES\fix-109-2\src\PBI-Tools\Win32\ProcessExtensions.cs:line 66
   at PbiTools.Utils.PowerBIProcesses.<EnumerateProcesses>d__1.MoveNext() in F:\pbi-tools\BRANCHES\fix-109-2\src\PBI-Tools\Utils\PowerBIProcesses.cs:line 26
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at PbiTools.Cli.CmdLineActions.Info(Boolean checkDownloadVersion) in F:\pbi-tools\BRANCHES\fix-109-2\src\PBI-Tools\Cli\Info.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in F:\pbi-tools\BRANCHES\fix-109-2\src\PBI-Tools\Program.cs:line 94

**Comment by mthierba** [comment] 2022-05-25 05:41
Ah, i see. This is not the exact same issue as the one reported by Marcus. Here, the problem appears to be the multi-user setup where conflicting processes are running under other users' accounts, as opposed to a Windows Service running under a service account. That's why the issue occurs earlier during execution and hence the exception is propagated. I know what to do, though, please give it a couple of days.

**Comment by marcosqlbi** [comment] 2022-06-10 17:02
I've found that the RC2 solves the problem if the tool runs with administrator rights. However, when I use a non-admin user, I still get this error:

``
An unhandled exception occurred.
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at PbiTools.Win32.ProcessExtensions.GetCommandLine(Process process)
   at PbiTools.Utils.PowerBIProcesses.<EnumerateProcesses>d__1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at PbiTools.Cli.CmdLineActions.Info(Boolean checkDownloadVersion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args)
``

The issue is caused by other SSAS instances running, if I stop SSAS services then it runs with a regular user.

**Comment by mthierba** [comment] 2022-06-10 17:45
@matherring @marcosqlbi Just committed a better fix for this issue which should cover all cases where `pbi-tools` chokes on another instance of SSAS on the same machine. It's currently available on https://github.com/pbi-tools/pbi-tools/tree/Issues/109-mt-2. You could build the tool yourself running `./build.cmd Pack` from the root. I'm planning to release another RC.2 pre-release over the weekend which will include this fix as well as lot of not XMLA deployment goodies ;)

**Closed** 2023-01-09 19:20 UTC
Labels: bug
