### ISSUE TITLE
How to create Project Folder in PBI Tools ?

### ISSUE THREAD

**Issue by MarkSteven123** [pbi-tools/pbi-tools#299] opened 2023-08-06 03:31 UTC
Hi Mathias, my Team uses PBI Tools to for deployment until now. We are planning to leverage Project Folder (.PBIP) introduced by Microsoft. However, we don't see an option in PBI Tools to convert from PBIX/PBIT to Project Folder and other way. Am I missing something? Please assist.

Thanks for your effort with PBI Tools.  I just sponsored you  in github.

**Comment by MarkSteven123** [comment] 2023-08-17 17:47
@mthierba   Just checking if you got a chance to look at my above Question. Thank you.

**Comment by mthierba** [comment] 2023-09-01 06:06
I'll tackle this at the end of September - currently buried under other obligations.

**Comment by mthierba** [comment] 2024-02-05 18:20
Duplicate of #303, which is now in progress.

**Closed by mthierba** 2024-02-05 18:20 UTC
